name: Weekly Dummy Update

on:
  schedule:
    # Runs every week on Sunday at midnight (00:00)
    - cron: '0 0 * * SUN' 
  workflow_dispatch:

jobs:
  update-dummy-md:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate random content
        id: generate_content
        run: |
          # Generate random content and save it into a variable
          RANDOM_CONTENT=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 100)
          echo "Random content: $RANDOM_CONTENT" > random_content.txt

      - name: Update dummy.md with random content
        run: |
          # Update dummy.md with the generated content
          echo "Random Data for this week: $(cat random_content.txt)" > dummy.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dummy.md
          git commit -m "Update dummy.md with random data"
          git push origin main

